import React, { useState, useEffect } from "react";
import { Search, ShoppingBag, Plus, FileText, CheckCircle2, AlertTriangle, Download } from "lucide-react";
import { Product, InventoryItem, LightClient, UserRole, UserProfile } from "../types";
import { formatCFA } from "../data";
import { billingService } from "../services/billingService";

interface POSComponentProps {
  currentUser: UserProfile;
  inventory: InventoryItem[];
  products: Product[];
  lightClients: LightClient[];
  posCart: Record<string, number>;
  onAddToCart: (prodId: string, qty: number) => void;
  onCheckout: (saleData: any) => Promise<void>;
  selectedClientId: string;
  setSelectedClientId: (id: string) => void;
  amountPaid: number;
  setAmountPaid: (amt: number) => void;
  title?: string;
}

export function POSComponent({
  currentUser,
  inventory,
  products,
  lightClients,
  posCart,
  onAddToCart,
  onCheckout,
  selectedClientId,
  setSelectedClientId,
  amountPaid,
  setAmountPaid,
  title = "Caisse Minute (POS Comptoir)"
}: POSComponentProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string>("ALL");
  // Determine available sale types based on role
  const role = currentUser.role;
  const isWholesaler = role === UserRole.WHOLESALER;
  const isRetailer = role === UserRole.RETAILER;
  
  const [typeVente, setTypeVente] = useState<"GROS" | "DETAIL">(isWholesaler ? "GROS" : "DETAIL");
  const [posCustomerType, setPosCustomerType] = useState<"RETAILER" | "CLIENT" | "LIGHT_CLIENT">("CLIENT");
  
  const [isProcessing, setIsProcessing] = useState(false);
  const [successFactureUrl, setSuccessFactureUrl] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Helper to get applicable price
  const getApplicablePrice = (invItem: InventoryItem) => {
    if (typeVente === "GROS") return invItem.prixGros || invItem.price;
    return invItem.prixDetail || invItem.price;
  };

  const totalAmount = Object.keys(posCart).reduce((sum, id) => {
    const invItem = inventory.find(i => i.productId === id);
    if (!invItem) return sum;
    return sum + (getApplicablePrice(invItem) * posCart[id]);
  }, 0);

  const handleValidation = async () => {
    setIsProcessing(true);
    setErrorMsg(null);
    setSuccessFactureUrl(null);
    try {
      // 1. Prepare lines
      const lignes = Object.keys(posCart)
        .filter(id => posCart[id] > 0)
        .map(id => {
          const qty = posCart[id];
          const prod = products.find(p => p.id === id);
          const invItem = inventory.find(i => i.productId === id);
          const prix = getApplicablePrice(invItem!);
          return {
            produitId: id,
            nom: prod?.name || "Produit Inconnu",
            quantite: qty,
            prixUnitaire: prix,
            sousTotal: prix * qty
          };
        });

      // 2. Format acheteur info
      let acheteurNom = "Client Final";
      if (posCustomerType === "LIGHT_CLIENT") {
        const lc = lightClients.find(c => c.id === selectedClientId);
        if (lc) acheteurNom = lc.name;
      } else if (posCustomerType === "RETAILER") {
        acheteurNom = "Client Détaillant (Anonyme)";
      }

      const factureData = {
        venteId: "tmp_" + Date.now(), // Will be generated by function ideally, but we simulate here
        vendeurId: currentUser.id,
        vendeurNom: currentUser.companyName || currentUser.name,
        vendeurRole: currentUser.role,
        acheteurId: selectedClientId || undefined,
        acheteurNom,
        typeVente,
        lignes,
        total: totalAmount
      };

      // 3. Appeler la fonction de checkout (qui simulera la Cloud Function ou mettra à jour l'état React)
      await onCheckout(factureData);

      // 4. Générer la facture PDF (Client side PDF generation)
      const pdfUrl = await billingService.genererEtEnregistrerFacture(factureData);
      
      setSuccessFactureUrl(pdfUrl);
    } catch (err: any) {
      setErrorMsg(err.message || "Erreur lors de l'enregistrement de la vente");
    } finally {
      setIsProcessing(false);
    }
  };

  if (successFactureUrl) {
    return (
      <div className="bg-white dark:bg-zinc-900 border border-emerald-200 dark:border-emerald-900/50 rounded-2xl p-8 text-center max-w-lg mx-auto">
        <div className="w-16 h-16 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
          <CheckCircle2 className="w-8 h-8" />
        </div>
        <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 mb-2">Vente validée avec succès</h3>
        <p className="text-sm text-zinc-500 mb-6">Le stock a été mis à jour et la facture générée.</p>
        <div className="flex gap-4 justify-center">
          <a
            href={successFactureUrl}
            target="_blank"
            rel="noopener noreferrer"
            download="Facture.pdf"
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition flex items-center gap-2 shadow-sm"
          >
            <Download className="w-4 h-4" /> Télécharger Facture
          </a>
          <button
            onClick={() => setSuccessFactureUrl(null)}
            className="px-4 py-2 bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700 text-xs font-bold rounded-xl transition"
          >
            Nouvelle Vente
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2 space-y-4">
        {errorMsg && (
          <div className="p-4 bg-rose-50 border border-rose-200 rounded-xl flex gap-3 items-center text-rose-700 text-sm font-medium">
            <AlertTriangle className="w-5 h-5 shrink-0" />
            <p>{errorMsg}</p>
          </div>
        )}
        
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white dark:bg-zinc-900 p-4 rounded-2xl border border-zinc-150 dark:border-zinc-800">
          <div className="relative flex-1 w-full">
            <Search className="w-4 h-4 absolute left-3 top-3 text-zinc-400" />
            <input
              type="text"
              placeholder="Rechercher un produit dans votre stock..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-zinc-50 dark:bg-zinc-800 border-none rounded-xl text-sm focus:ring-2 focus:ring-emerald-500 transition shadow-inner"
            />
          </div>
          
          {/* Mode de vente (Gros vs Détail) */}
          <div className="flex bg-zinc-100 dark:bg-zinc-800 p-1 rounded-xl shrink-0 w-full sm:w-auto">
            <button
              onClick={() => setTypeVente("GROS")}
              disabled={isRetailer}
              className={`flex-1 sm:flex-none px-4 py-1.5 text-xs font-bold rounded-lg transition ${typeVente === "GROS" ? "bg-white dark:bg-zinc-700 shadow-sm text-zinc-900 dark:text-white" : "text-zinc-500 hover:text-zinc-700"} ${isRetailer ? "opacity-50 cursor-not-allowed" : ""}`}
            >
              Gros
            </button>
            <button
              onClick={() => setTypeVente("DETAIL")}
              disabled={isWholesaler}
              className={`flex-1 sm:flex-none px-4 py-1.5 text-xs font-bold rounded-lg transition ${typeVente === "DETAIL" ? "bg-white dark:bg-zinc-700 shadow-sm text-zinc-900 dark:text-white" : "text-zinc-500 hover:text-zinc-700"} ${isWholesaler ? "opacity-50 cursor-not-allowed" : ""}`}
            >
              Détail
            </button>
          </div>
        </div>

        {/* Category Filter Pills in POS */}
        {(() => {
          const categoriesSet = new Set<string>();
          inventory.forEach(item => {
            const prod = products.find(p => p.id === item.productId);
            if (prod && prod.category) categoriesSet.add(prod.category);
          });
          const categories = Array.from(categoriesSet);
          if (categories.length === 0) return null;

          return (
            <div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-none items-center">
              <button
                onClick={() => setSelectedCategory("ALL")}
                className={`px-3 py-1 text-xs font-bold rounded-lg transition whitespace-nowrap cursor-pointer ${
                  selectedCategory === "ALL"
                    ? "bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 shadow-xs"
                    : "bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50"
                }`}
              >
                Tous ({inventory.length})
              </button>
              {categories.map((cat) => {
                const count = inventory.filter(item => {
                  const prod = products.find(p => p.id === item.productId);
                  return prod?.category === cat;
                }).length;
                return (
                  <button
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-3 py-1 text-xs font-bold rounded-lg transition whitespace-nowrap cursor-pointer ${
                      selectedCategory === cat
                        ? "bg-emerald-600 text-white shadow-xs"
                        : "bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50"
                    }`}
                  >
                    {cat} ({count})
                  </button>
                );
              })}
            </div>
          );
        })()}

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-[500px] overflow-y-auto pr-1 scrollbar-thin">
          {inventory
            .filter(item => {
              const prod = products.find(p => p.id === item.productId);
              if (!prod) return false;
              const matchesSearch = prod.name.toLowerCase().includes(searchQuery.toLowerCase()) || (prod.category && prod.category.toLowerCase().includes(searchQuery.toLowerCase()));
              const matchesCategory = selectedCategory === "ALL" || prod.category === selectedCategory;
              return matchesSearch && matchesCategory;
            })
            .map((item) => {
            const prod = products.find((p) => p.id === item.productId);
            if (!prod) return null;
            const prixAffiche = getApplicablePrice(item);
            
            return (
              <div key={item.id} className="p-3 bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 rounded-xl flex items-center justify-between shadow-xs hover:border-emerald-200 dark:hover:border-emerald-900/30 transition-colors">
                <div className="flex gap-3 items-center min-w-0">
                  <div className="w-10 h-10 rounded-lg bg-zinc-100 dark:bg-zinc-800 flex-shrink-0 overflow-hidden">
                    <img loading="lazy" src={prod.image} alt={prod.name} className="w-full h-full object-cover" />
                  </div>
                  <div className="min-w-0">
                    <p className="font-bold text-[11px] text-zinc-950 dark:text-white truncate">{prod.name}</p>
                    <p className="text-[10px] text-zinc-500 font-medium">En Stock: {item.stock}</p>
                    <p className="text-[11px] font-bold text-emerald-600 mt-0.5">{formatCFA(prixAffiche)}</p>
                  </div>
                </div>
                <div className="flex items-center gap-1.5 bg-zinc-50 dark:bg-zinc-950/50 p-1 rounded-lg border border-zinc-100 dark:border-zinc-800">
                  <button
                    onClick={() => onAddToCart(prod.id, -1)}
                    className="w-7 h-7 rounded-md bg-white dark:bg-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-700 text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-zinc-700 shadow-sm transition-all active:scale-95 flex items-center justify-center font-bold"
                  >
                    -
                  </button>
                  <span className="w-8 text-center text-xs font-bold text-zinc-900 dark:text-white">{posCart[prod.id] || 0}</span>
                  <button
                    onClick={() => onAddToCart(prod.id, 1)}
                    disabled={item.stock <= (posCart[prod.id] || 0)}
                    className="w-7 h-7 rounded-md bg-white dark:bg-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-700 text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-zinc-700 shadow-sm transition-all active:scale-95 flex items-center justify-center font-bold disabled:opacity-50"
                  >
                    +
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <div className="p-5 bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-800 rounded-2xl shadow-sm space-y-5 sticky top-4">
          <div className="flex items-center justify-between pb-2 border-b border-zinc-100 dark:border-zinc-800">
            <h5 className="font-bold text-xs text-zinc-900 dark:text-zinc-100 uppercase tracking-widest flex items-center gap-2">
              <ShoppingBag className="w-4 h-4 text-emerald-600" /> Caisse ({typeVente})
            </h5>
          </div>
          
          <div className="space-y-3 max-h-60 overflow-y-auto pr-1 scrollbar-none">
            {Object.keys(posCart).filter(id => posCart[id] > 0).length === 0 ? (
              <div className="py-6 text-center text-zinc-400 italic text-[11px]">Le panier est vide.</div>
            ) : (
              Object.keys(posCart)
                .filter((prodId) => posCart[prodId] > 0)
                .map((prodId) => {
                  const qty = posCart[prodId];
                  const prod = products.find((p) => p.id === prodId);
                  const invItem = inventory.find((i) => i.productId === prodId);
                  const px = getApplicablePrice(invItem!);
                  return (
                    <div key={prodId} className="flex justify-between items-start text-[11px]">
                      <div className="min-w-0 flex-1 pr-2">
                        <p className="font-semibold text-zinc-800 dark:text-zinc-200 truncate">{prod?.name}</p>
                        <p className="text-[10px] text-zinc-400">{qty} x {formatCFA(px)}</p>
                      </div>
                      <span className="font-bold text-zinc-900 dark:text-white whitespace-nowrap">{formatCFA(px * qty)}</span>
                    </div>
                  );
                })
            )}
          </div>

          <div className="pt-4 border-t border-zinc-100 dark:border-zinc-800 space-y-4">
            <div className="space-y-2">
              <label className="text-[10px] uppercase font-bold text-zinc-500 tracking-wider">Acheteur</label>
              <select 
                value={posCustomerType}
                onChange={(e) => setPosCustomerType(e.target.value as any)}
                className="w-full bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl p-2 text-xs focus:ring-2 focus:ring-emerald-500 transition"
              >
                <option value="CLIENT">Client Anonyme</option>
                <option value="RETAILER">Autre Commerçant</option>
                <option value="LIGHT_CLIENT">Client Fidèle (Crédit)</option>
              </select>
            </div>

            {posCustomerType === "LIGHT_CLIENT" && (
            <div className="space-y-2">
              <select 
                value={selectedClientId}
                onChange={(e) => setSelectedClientId(e.target.value)}
                className="w-full bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl p-2 text-xs focus:ring-2 focus:ring-emerald-500 transition"
              >
                <option value="">Sélectionner un client...</option>
                {lightClients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            )}

            <div className="bg-emerald-50 dark:bg-emerald-900/10 p-4 rounded-xl border border-emerald-100 dark:border-emerald-900/20">
              <div className="flex justify-between items-center">
                <span className="text-xs font-bold text-emerald-800 dark:text-emerald-400">TOTAL À PAYER</span>
                <span className="text-lg font-black text-emerald-900 dark:text-emerald-200 font-mono">{formatCFA(totalAmount)}</span>
              </div>
            </div>

            <button
              onClick={handleValidation}
              disabled={Object.keys(posCart).filter(id => posCart[id] > 0).length === 0 || isProcessing}
              className="w-full bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 disabled:hover:bg-emerald-600 text-white py-3 rounded-xl font-bold transition-all shadow-lg shadow-emerald-600/20 active:scale-95 flex items-center justify-center gap-2"
            >
              {isProcessing ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
              ) : (
                <><FileText className="w-4 h-4" /> Valider & Générer Facture</>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
